name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  cancel_previous:
    permissions: write-all
    runs-on: ubuntu-latest-large
    steps:
    - uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b  # 0.9.1
      with:
        workflow_id: ${{ github.event.workflow.id }}

  build:

    needs: cancel_previous
    runs-on: ubuntu-latest-large

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: cache gradle dependencies
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Run Tests
      run: ./gradlew check
